Lesson2
artpetrovskii/Head-First-Ruby pull request #2
Opened 2020-07-22 13:32 UTC by artpetrovskii

2020-07-27 15:08 UTC, apetrovskiy requested changes

2020-07-27 15:08 UTC, apetrovskiy commented on Blender.rb
> +  def blend (speed)
There should be an empty line between methods.

2020-07-27 15:08 UTC, apetrovskiy commented on animals.rb
> +dog.talk
The talk method requires one argument

2020-07-27 15:08 UTC, apetrovskiy commented on animals.rb
> +cat.move("house")
The move method requires two arguments.

2020-07-27 15:08 UTC, apetrovskiy commented on Blender.rb
> +  def blend (speed)
rubocop: there should be an empty line,

2020-07-27 15:08 UTC, apetrovskiy commented on dog.rb
> +  @name = value
indentation

2020-07-27 15:08 UTC, apetrovskiy commented on dog.rb
> +  @age = value
indentation

2020-07-27 15:08 UTC, apetrovskiy commented on mage.rb
> +morgana.enchant(merlin)
There're numerous style issues
![image](https://user-images.githubusercontent.com/2947151/88511843-37968980-cfee-11ea-90aa-480ae2b53b9e.png)
![image](https://user-images.githubusercontent.com/2947151/88512992-20f13200-cff0-11ea-9da3-fca8b7e8364b.png)

2020-07-27 15:08 UTC, apetrovskiy commented on MyClass.rb
> +my_instance.my_attribute=("same here")
There're extra parentheses while lack of spaces

2020-07-27 15:08 UTC, apetrovskiy commented on Widget.rb
> +widget.show_size
The script doesn't work:
```
[Running] ruby "c:\Projects\Artemii\Head-First-Ruby\Widget.rb"
Size:

2020-07-28 15:12 UTC, artpetrovskii commented on Blender.rb
> +  def blend (speed)
I fixed it

2020-07-28 15:12 UTC, artpetrovskii commented on Blender.rb
> +  def blend (speed)
I fixed it

2020-07-28 15:17 UTC, artpetrovskii commented on dog.rb
> +  @name = value
I fixed it

2020-07-28 15:17 UTC, artpetrovskii commented on dog.rb
> +  @age = value
I fixed it

2020-07-28 17:54 UTC, artpetrovskii commented on dog.rb
> +  @age = value
I fixed it

2020-08-01 15:04 UTC, apetrovskiy commented on animals.rb
> +dog.talk
It doesn't work:
```
[Running] ruby "c:\Projects\Ruby\Head-First-Ruby\animals.rb"
c:/Projects/Ruby/Head-First-Ruby/animals.rb:5:in `move': wrong number of arguments (given 1, expected 2) (ArgumentError)
	from c:/Projects/Ruby/Head-First-Ruby/animals.rb:32:in `<main>'

[Done] exited with code=1 in 9.396 seconds
```

2020-08-01 17:07 UTC, artpetrovskii commented on animals.rb
> +cat.move("house")
I fixed it

2020-08-01 17:07 UTC, artpetrovskii commented on animals.rb
> +dog.talk
I fixed it

2020-08-01 17:09 UTC, artpetrovskii commented on mage.rb
> +morgana.enchant(merlin)
I fixed it

2020-08-01 19:31 UTC, apetrovskiy commented on Blender.rb
> +  def blend (speed)
Resolve conversations, please

2020-08-01 19:39 UTC, apetrovskiy requested changes

2020-08-01 19:39 UTC, apetrovskiy commented on Blender.rb
> +class Blender
filename

2020-08-01 19:39 UTC, apetrovskiy commented on dog.rb
> +    if value < 0
value.negative?

2020-08-01 19:39 UTC, apetrovskiy commented on MyClass.rb
> +class MyClass
file name

2020-08-01 19:39 UTC, apetrovskiy commented on vehicle_methods.rb
> +  if gas_used == 0
gas_user.zero?

2020-08-02 17:43 UTC, artpetrovskii commented on MyClass.rb
> +my_instance.my_attribute=("same here")
I fixed it

2020-08-02 17:51 UTC, artpetrovskii commented on Blender.rb
> +class Blender
I fixed it

2020-08-02 17:51 UTC, artpetrovskii commented on MyClass.rb
> +class MyClass
I fixed it

2020-08-02 18:25 UTC, artpetrovskii commented on dog.rb
> +    if value < 0
I fixed it

2020-08-02 18:25 UTC, artpetrovskii commented on vehicle_methods.rb
> +  if gas_used == 0
I fixed it

2020-08-03 06:19 UTC, artpetrovskii commented on Blender.rb
> +class Blender
I fixed it

2020-08-03 06:19 UTC, artpetrovskii commented on MyClass.rb
> +class MyClass
I fixed it

2020-08-03 07:25 UTC, artpetrovskii commented on Widget.rb
> +widget.show_size
I fixed it

2020-08-05 09:19 UTC, apetrovskiy approved these changes

2020-08-05 09:20 UTC, merged